name: 'build-project'

on:
  push:
    branches: [ main ]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.8.1'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
  eslint:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Run ESLint
        run: pnpm run lint
  eslintfix:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Run ESLint
        run: pnpm run lint:fix
